(function () {
    'use strict';

    angular.module('BlurAdmin.theme')
    .service('isoCountries', function () {

        var countriesMap = {
            "AF": {"alpha-2": "AF", "name": "Afghanistan", "region": "Asia"},
            "AX": {"alpha-2": "AX", "name": "Åland Islands", "region": "Europe"},
            "AL": {"alpha-2": "AL", "name": "Albania", "region": "Europe"},
            "DZ": {"alpha-2": "DZ", "name": "Algeria", "region": "Africa"},
            "AS": {"alpha-2": "AS", "name": "American Samoa", "region": "Oceania"},
            "AD": {"alpha-2": "AD", "name": "Andorra", "region": "Europe"},
            "AO": {"alpha-2": "AO", "name": "Angola", "region": "Africa"},
            "AI": {"alpha-2": "AI", "name": "Anguilla", "region": "Americas"},
            "AQ": {"alpha-2": "AQ", "name": "Antarctica", "region": null},
            "AG": {"alpha-2": "AG", "name": "Antigua and Barbuda", "region": "Americas"},
            "AR": {"alpha-2": "AR", "name": "Argentina", "region": "Americas"},
            "AM": {"alpha-2": "AM", "name": "Armenia", "region": "Asia"},
            "AW": {"alpha-2": "AW", "name": "Aruba", "region": "Americas"},
            "AU": {"alpha-2": "AU", "name": "Australia", "region": "Oceania"},
            "AT": {"alpha-2": "AT", "name": "Austria", "region": "Europe"},
            "AZ": {"alpha-2": "AZ", "name": "Azerbaijan", "region": "Asia"},
            "BS": {"alpha-2": "BS", "name": "Bahamas", "region": "Americas"},
            "BH": {"alpha-2": "BH", "name": "Bahrain", "region": "Asia"},
            "BD": {"alpha-2": "BD", "name": "Bangladesh", "region": "Asia"},
            "BB": {"alpha-2": "BB", "name": "Barbados", "region": "Americas"},
            "BY": {"alpha-2": "BY", "name": "Belarus", "region": "Europe"},
            "BE": {"alpha-2": "BE", "name": "Belgium", "region": "Europe"},
            "BZ": {"alpha-2": "BZ", "name": "Belize", "region": "Americas"},
            "BJ": {"alpha-2": "BJ", "name": "Benin", "region": "Africa"},
            "BM": {"alpha-2": "BM", "name": "Bermuda", "region": "Americas"},
            "BT": {"alpha-2": "BT", "name": "Bhutan", "region": "Asia"},
            "BO": {"alpha-2": "BO", "name": "Bolivia", "region": "Americas"},
            "BQ": {"alpha-2": "BQ", "name": "Bonaire, Sint Eustatius and Saba", "region": "Americas"},
            "BA": {"alpha-2": "BA", "name": "Bosnia and Herzegovina", "region": "Europe"},
            "BW": {"alpha-2": "BW", "name": "Botswana", "region": "Africa"},
            "BV": {"alpha-2": "BV", "name": "Bouvet Island", "region": null},
            "BR": {"alpha-2": "BR", "name": "Brazil", "region": "Americas"},
            "IO": {"alpha-2": "IO", "name": "British Indian Ocean Territory", "region": null},
            "BN": {"alpha-2": "BN", "name": "Brunei Darussalam", "region": "Asia"},
            "BG": {"alpha-2": "BG", "name": "Bulgaria", "region": "Europe"},
            "BF": {"alpha-2": "BF", "name": "Burkina Faso", "region": "Africa"},
            "BI": {"alpha-2": "BI", "name": "Burundi", "region": "Africa"},
            "KH": {"alpha-2": "KH", "name": "Cambodia", "region": "Asia"},
            "CM": {"alpha-2": "CM", "name": "Cameroon", "region": "Africa"},
            "CA": {"alpha-2": "CA", "name": "Canada", "region": "Americas"},
            "CV": {"alpha-2": "CV", "name": "Cabo Verde", "region": "Africa"},
            "KY": {"alpha-2": "KY", "name": "Cayman Islands", "region": "Americas"},
            "CF": {"alpha-2": "CF", "name": "Central African Republic", "region": "Africa"},
            "TD": {"alpha-2": "TD", "name": "Chad", "region": "Africa"},
            "CL": {"alpha-2": "CL", "name": "Chile", "region": "Americas"},
            "CN": {"alpha-2": "CN", "name": "China", "region": "Asia"},
            "CX": {"alpha-2": "CX", "name": "Christmas Island", "region": null},
            "CC": {"alpha-2": "CC", "name": "Cocos (Keeling) Islands", "region": null},
            "CO": {"alpha-2": "CO", "name": "Colombia", "region": "Americas"},
            "KM": {"alpha-2": "KM", "name": "Comoros", "region": "Africa"},
            "CG": {"alpha-2": "CG", "name": "Congo", "region": "Africa"},
            "CD": {"alpha-2": "CD", "name": "Congo (Democratic Republic of the)", "region": "Africa"},
            "CK": {"alpha-2": "CK", "name": "Cook Islands", "region": "Oceania"},
            "CR": {"alpha-2": "CR", "name": "Costa Rica", "region": "Americas"},
            "CI": {"alpha-2": "CI", "name": "Côte d'Ivoire", "region": "Africa"},
            "HR": {"alpha-2": "HR", "name": "Croatia", "region": "Europe"},
            "CU": {"alpha-2": "CU", "name": "Cuba", "region": "Americas"},
            "CW": {"alpha-2": "CW", "name": "Curaçao", "region": "Americas"},
            "CY": {"alpha-2": "CY", "name": "Cyprus", "region": "Asia"},
            "CZ": {"alpha-2": "CZ", "name": "Czech Republic", "region": "Europe"},
            "DK": {"alpha-2": "DK", "name": "Denmark", "region": "Europe"},
            "DJ": {"alpha-2": "DJ", "name": "Djibouti", "region": "Africa"},
            "DM": {"alpha-2": "DM", "name": "Dominica", "region": "Americas"},
            "DO": {"alpha-2": "DO", "name": "Dominican Republic", "region": "Americas"},
            "EC": {"alpha-2": "EC", "name": "Ecuador", "region": "Americas"},
            "EG": {"alpha-2": "EG", "name": "Egypt", "region": "Africa"},
            "SV": {"alpha-2": "SV", "name": "El Salvador", "region": "Americas"},
            "GQ": {"alpha-2": "GQ", "name": "Equatorial Guinea", "region": "Africa"},
            "ER": {"alpha-2": "ER", "name": "Eritrea", "region": "Africa"},
            "EE": {"alpha-2": "EE", "name": "Estonia", "region": "Europe"},
            "ET": {"alpha-2": "ET", "name": "Ethiopia", "region": "Africa"},
            "FK": {"alpha-2": "FK", "name": "Falkland Islands (Malvinas)", "region": "Americas"},
            "FO": {"alpha-2": "FO", "name": "Faroe Islands", "region": "Europe"},
            "FJ": {"alpha-2": "FJ", "name": "Fiji", "region": "Oceania"},
            "FI": {"alpha-2": "FI", "name": "Finland", "region": "Europe"},
            "FR": {"alpha-2": "FR", "name": "France", "region": "Europe"},
            "GF": {"alpha-2": "GF", "name": "French Guiana", "region": "Americas"},
            "PF": {"alpha-2": "PF", "name": "French Polynesia", "region": "Oceania"},
            "TF": {"alpha-2": "TF", "name": "French Southern Territories", "region": null},
            "GA": {"alpha-2": "GA", "name": "Gabon", "region": "Africa"},
            "GM": {"alpha-2": "GM", "name": "Gambia", "region": "Africa"},
            "GE": {"alpha-2": "GE", "name": "Georgia", "region": "Asia"},
            "DE": {"alpha-2": "DE", "name": "Germany", "region": "Europe"},
            "GH": {"alpha-2": "GH", "name": "Ghana", "region": "Africa"},
            "GI": {"alpha-2": "GI", "name": "Gibraltar", "region": "Europe"},
            "GR": {"alpha-2": "GR", "name": "Greece", "region": "Europe"},
            "GL": {"alpha-2": "GL", "name": "Greenland", "region": "Americas"},
            "GD": {"alpha-2": "GD", "name": "Grenada", "region": "Americas"},
            "GP": {"alpha-2": "GP", "name": "Guadeloupe", "region": "Americas"},
            "GU": {"alpha-2": "GU", "name": "Guam", "region": "Oceania"},
            "GT": {"alpha-2": "GT", "name": "Guatemala", "region": "Americas"},
            "GG": {"alpha-2": "GG", "name": "Guernsey", "region": "Europe"},
            "GN": {"alpha-2": "GN", "name": "Guinea", "region": "Africa"},
            "GW": {"alpha-2": "GW", "name": "Guinea-Bissau", "region": "Africa"},
            "GY": {"alpha-2": "GY", "name": "Guyana", "region": "Americas"},
            "HT": {"alpha-2": "HT", "name": "Haiti", "region": "Americas"},
            "HM": {"alpha-2": "HM", "name": "Heard Island and McDonald Islands", "region": null},
            "VA": {"alpha-2": "VA", "name": "Holy See", "region": "Europe"},
            "HN": {"alpha-2": "HN", "name": "Honduras", "region": "Americas"},
            "HK": {"alpha-2": "HK", "name": "Hong Kong", "region": "Asia"},
            "HU": {"alpha-2": "HU", "name": "Hungary", "region": "Europe"},
            "IS": {"alpha-2": "IS", "name": "Iceland", "region": "Europe"},
            "IN": {"alpha-2": "IN", "name": "India", "region": "Asia"},
            "ID": {"alpha-2": "ID", "name": "Indonesia", "region": "Asia"},
            "IR": {"alpha-2": "IR", "name": "Iran (Islamic Republic of)", "region": "Asia"},
            "IQ": {"alpha-2": "IQ", "name": "Iraq", "region": "Asia"},
            "IE": {"alpha-2": "IE", "name": "Ireland", "region": "Europe"},
            "IM": {"alpha-2": "IM", "name": "Isle of Man", "region": "Europe"},
            "IL": {"alpha-2": "IL", "name": "Israel", "region": "Asia"},
            "IT": {"alpha-2": "IT", "name": "Italy", "region": "Europe"},
            "JM": {"alpha-2": "JM", "name": "Jamaica", "region": "Americas"},
            "JP": {"alpha-2": "JP", "name": "Japan", "region": "Asia"},
            "JE": {"alpha-2": "JE", "name": "Jersey", "region": "Europe"},
            "JO": {"alpha-2": "JO", "name": "Jordan", "region": "Asia"},
            "KZ": {"alpha-2": "KZ", "name": "Kazakhstan", "region": "Asia"},
            "KE": {"alpha-2": "KE", "name": "Kenya", "region": "Africa"},
            "KI": {"alpha-2": "KI", "name": "Kiribati", "region": "Oceania"},
            "KP": {"alpha-2": "KP", "name": "Korea (Democratic Republic of)", "region": "Asia"},
            "KR": {"alpha-2": "KR", "name": "Korea (Republic of)", "region": "Asia"},
            "KW": {"alpha-2": "KW", "name": "Kuwait", "region": "Asia"},
            "KG": {"alpha-2": "KG", "name": "Kyrgyzstan", "region": "Asia"},
            "LA": {"alpha-2": "LA", "name": "Lao People's Democratic Republic", "region": "Asia"},
            "LV": {"alpha-2": "LV", "name": "Latvia", "region": "Europe"},
            "LB": {"alpha-2": "LB", "name": "Lebanon", "region": "Asia"},
            "LS": {"alpha-2": "LS", "name": "Lesotho", "region": "Africa"},
            "LR": {"alpha-2": "LR", "name": "Liberia", "region": "Africa"},
            "LY": {"alpha-2": "LY", "name": "Libya", "region": "Africa"},
            "LI": {"alpha-2": "LI", "name": "Liechtenstein", "region": "Europe"},
            "LT": {"alpha-2": "LT", "name": "Lithuania", "region": "Europe"},
            "LU": {"alpha-2": "LU", "name": "Luxembourg", "region": "Europe"},
            "MO": {"alpha-2": "MO", "name": "Macao", "region": "Asia"},
            "MK": {"alpha-2": "MK", "name": "Macedonia", "region": "Europe"},
            "MG": {"alpha-2": "MG", "name": "Madagascar", "region": "Africa"},
            "MW": {"alpha-2": "MW", "name": "Malawi", "region": "Africa"},
            "MY": {"alpha-2": "MY", "name": "Malaysia", "region": "Asia"},
            "MV": {"alpha-2": "MV", "name": "Maldives", "region": "Asia"},
            "ML": {"alpha-2": "ML", "name": "Mali", "region": "Africa"},
            "MT": {"alpha-2": "MT", "name": "Malta", "region": "Europe"},
            "MH": {"alpha-2": "MH", "name": "Marshall Islands", "region": "Oceania"},
            "MQ": {"alpha-2": "MQ", "name": "Martinique", "region": "Americas"},
            "MR": {"alpha-2": "MR", "name": "Mauritania", "region": "Africa"},
            "MU": {"alpha-2": "MU", "name": "Mauritius", "region": "Africa"},
            "YT": {"alpha-2": "YT", "name": "Mayotte", "region": "Africa"},
            "MX": {"alpha-2": "MX", "name": "Mexico", "region": "Americas"},
            "FM": {"alpha-2": "FM", "name": "Micronesia (Federated States of)", "region": "Oceania"},
            "MD": {"alpha-2": "MD", "name": "Moldova (Republic of)", "region": "Europe"},
            "MC": {"alpha-2": "MC", "name": "Monaco", "region": "Europe"},
            "MN": {"alpha-2": "MN", "name": "Mongolia", "region": "Asia"},
            "ME": {"alpha-2": "ME", "name": "Montenegro", "region": "Europe"},
            "MS": {"alpha-2": "MS", "name": "Montserrat", "region": "Americas"},
            "MA": {"alpha-2": "MA", "name": "Morocco", "region": "Africa"},
            "MZ": {"alpha-2": "MZ", "name": "Mozambique", "region": "Africa"},
            "MM": {"alpha-2": "MM", "name": "Myanmar", "region": "Asia"},
            "NA": {"alpha-2": "NA", "name": "Namibia", "region": "Africa"},
            "NR": {"alpha-2": "NR", "name": "Nauru", "region": "Oceania"},
            "NP": {"alpha-2": "NP", "name": "Nepal", "region": "Asia"},
            "NL": {"alpha-2": "NL", "name": "Netherlands", "region": "Europe"},
            "NC": {"alpha-2": "NC", "name": "New Caledonia", "region": "Oceania"},
            "NZ": {"alpha-2": "NZ", "name": "New Zealand", "region": "Oceania"},
            "NI": {"alpha-2": "NI", "name": "Nicaragua", "region": "Americas"},
            "NE": {"alpha-2": "NE", "name": "Niger", "region": "Africa"},
            "NG": {"alpha-2": "NG", "name": "Nigeria", "region": "Africa"},
            "NU": {"alpha-2": "NU", "name": "Niue", "region": "Oceania"},
            "NF": {"alpha-2": "NF", "name": "Norfolk Island", "region": "Oceania"},
            "MP": {"alpha-2": "MP", "name": "Northern Mariana Islands", "region": "Oceania"},
            "NO": {"alpha-2": "NO", "name": "Norway", "region": "Europe"},
            "OM": {"alpha-2": "OM", "name": "Oman", "region": "Asia"},
            "PK": {"alpha-2": "PK", "name": "Pakistan", "region": "Asia"},
            "PW": {"alpha-2": "PW", "name": "Palau", "region": "Oceania"},
            "PS": {"alpha-2": "PS", "name": "Palestine, State of", "region": "Asia"},
            "PA": {"alpha-2": "PA", "name": "Panama", "region": "Americas"},
            "PG": {"alpha-2": "PG", "name": "Papua New Guinea", "region": "Oceania"},
            "PY": {"alpha-2": "PY", "name": "Paraguay", "region": "Americas"},
            "PE": {"alpha-2": "PE", "name": "Peru", "region": "Americas"},
            "PH": {"alpha-2": "PH", "name": "Philippines", "region": "Asia"},
            "PN": {"alpha-2": "PN", "name": "Pitcairn", "region": "Oceania"},
            "PL": {"alpha-2": "PL", "name": "Poland", "region": "Europe"},
            "PT": {"alpha-2": "PT", "name": "Portugal", "region": "Europe"},
            "PR": {"alpha-2": "PR", "name": "Puerto Rico", "region": "Americas"},
            "QA": {"alpha-2": "QA", "name": "Qatar", "region": "Asia"},
            "RE": {"alpha-2": "RE", "name": "Réunion", "region": "Africa"},
            "RO": {"alpha-2": "RO", "name": "Romania", "region": "Europe"},
            "RU": {"alpha-2": "RU", "name": "Russian Federation", "region": "Europe"},
            "RW": {"alpha-2": "RW", "name": "Rwanda", "region": "Africa"},
            "BL": {"alpha-2": "BL", "name": "Saint Barthélemy", "region": "Americas"},
            "SH": {"alpha-2": "SH", "name": "Saint Helena, Ascension and Tristan da Cunha", "region": "Africa"},
            "KN": {"alpha-2": "KN", "name": "Saint Kitts and Nevis", "region": "Americas"},
            "LC": {"alpha-2": "LC", "name": "Saint Lucia", "region": "Americas"},
            "MF": {"alpha-2": "MF", "name": "Saint Martin (French part)", "region": "Americas"},
            "PM": {"alpha-2": "PM", "name": "Saint Pierre and Miquelon", "region": "Americas"},
            "VC": {"alpha-2": "VC", "name": "Saint Vincent and the Grenadines", "region": "Americas"},
            "WS": {"alpha-2": "WS", "name": "Samoa", "region": "Oceania"},
            "SM": {"alpha-2": "SM", "name": "San Marino", "region": "Europe"},
            "ST": {"alpha-2": "ST", "name": "Sao Tome and Principe", "region": "Africa"},
            "SA": {"alpha-2": "SA", "name": "Saudi Arabia", "region": "Asia"},
            "SN": {"alpha-2": "SN", "name": "Senegal", "region": "Africa"},
            "RS": {"alpha-2": "RS", "name": "Serbia", "region": "Europe"},
            "SC": {"alpha-2": "SC", "name": "Seychelles", "region": "Africa"},
            "SL": {"alpha-2": "SL", "name": "Sierra Leone", "region": "Africa"},
            "SG": {"alpha-2": "SG", "name": "Singapore", "region": "Asia"},
            "SX": {"alpha-2": "SX", "name": "Sint Maarten (Dutch part)", "region": "Americas"},
            "SK": {"alpha-2": "SK", "name": "Slovakia", "region": "Europe"},
            "SI": {"alpha-2": "SI", "name": "Slovenia", "region": "Europe"},
            "SB": {"alpha-2": "SB", "name": "Solomon Islands", "region": "Oceania"},
            "SO": {"alpha-2": "SO", "name": "Somalia", "region": "Africa"},
            "ZA": {"alpha-2": "ZA", "name": "South Africa", "region": "Africa"},
            "GS": {"alpha-2": "GS", "name": "South Georgia and the South Sandwich Islands", "region": null},
            "SS": {"alpha-2": "SS", "name": "South Sudan", "region": "Africa"},
            "ES": {"alpha-2": "ES", "name": "Spain", "region": "Europe"},
            "LK": {"alpha-2": "LK", "name": "Sri Lanka", "region": "Asia"},
            "SD": {"alpha-2": "SD", "name": "Sudan", "region": "Africa"},
            "SR": {"alpha-2": "SR", "name": "Suriname", "region": "Americas"},
            "SJ": {"alpha-2": "SJ", "name": "Svalbard and Jan Mayen", "region": "Europe"},
            "SZ": {"alpha-2": "SZ", "name": "Swaziland", "region": "Africa"},
            "SE": {"alpha-2": "SE", "name": "Sweden", "region": "Europe"},
            "CH": {"alpha-2": "CH", "name": "Switzerland", "region": "Europe"},
            "SY": {"alpha-2": "SY", "name": "Syrian Arab Republic", "region": "Asia"},
            "TW": {"alpha-2": "TW", "name": "Taiwan, Province of China", "region": "Asia"},
            "TJ": {"alpha-2": "TJ", "name": "Tajikistan", "region": "Asia"},
            "TZ": {"alpha-2": "TZ", "name": "Tanzania, United Republic of", "region": "Africa"},
            "TH": {"alpha-2": "TH", "name": "Thailand", "region": "Asia"},
            "TL": {"alpha-2": "TL", "name": "Timor-Leste", "region": "Asia"},
            "TG": {"alpha-2": "TG", "name": "Togo", "region": "Africa"},
            "TK": {"alpha-2": "TK", "name": "Tokelau", "region": "Oceania"},
            "TO": {"alpha-2": "TO", "name": "Tonga", "region": "Oceania"},
            "TT": {"alpha-2": "TT", "name": "Trinidad and Tobago", "region": "Americas"},
            "TN": {"alpha-2": "TN", "name": "Tunisia", "region": "Africa"},
            "TR": {"alpha-2": "TR", "name": "Turkey", "region": "Asia"},
            "TM": {"alpha-2": "TM", "name": "Turkmenistan", "region": "Asia"},
            "TC": {"alpha-2": "TC", "name": "Turks and Caicos Islands", "region": "Americas"},
            "TV": {"alpha-2": "TV", "name": "Tuvalu", "region": "Oceania"},
            "UG": {"alpha-2": "UG", "name": "Uganda", "region": "Africa"},
            "UA": {"alpha-2": "UA", "name": "Ukraine", "region": "Europe"},
            "AE": {"alpha-2": "AE", "name": "United Arab Emirates", "region": "Asia"},
            "GB": {"alpha-2": "GB", "name": "United Kingdom", "region": "Europe"},
            "US": {"alpha-2": "US", "name": "United States of America", "region": "Americas"},
            "UM": {"alpha-2": "UM", "name": "United States Minor Outlying Islands", "region": null},
            "UY": {"alpha-2": "UY", "name": "Uruguay", "region": "Americas"},
            "UZ": {"alpha-2": "UZ", "name": "Uzbekistan", "region": "Asia"},
            "VU": {"alpha-2": "VU", "name": "Vanuatu", "region": "Oceania"},
            "VE": {"alpha-2": "VE", "name": "Venezuela", "region": "Americas"},
            "VN": {"alpha-2": "VN", "name": "Viet Nam", "region": "Asia"},
            "VG": {"alpha-2": "VG", "name": "Virgin Islands (British)", "region": "Americas"},
            "VI": {"alpha-2": "VI", "name": "Virgin Islands (U.S.)", "region": "Americas"},
            "WF": {"alpha-2": "WF", "name": "Wallis and Futuna", "region": "Oceania"},
            "EH": {"alpha-2": "EH", "name": "Western Sahara", "region": "Africa"},
            "YE": {"alpha-2": "YE", "name": "Yemen", "region": "Asia"},
            "ZM": {"alpha-2": "ZM", "name": "Zambia", "region": "Africa"},
            "ZW": {"alpha-2": "ZW", "name": "Zimbabwe", "region": "Africa"}
        };

        return {
            getName: function (code) {
                var country = countriesMap[code.toUpperCase()];
                return country ? country.name : code;
            }
        };

    });

})();

